server:
  port: 8081
spring:
  mail:
    default-encoding: utf-8
    host: smtp.163.com
    username: Ranshixu@163.com
    password: JZQDIGQFAVMDVMXM
  datasource:
    url: jdbc:mysql://localhost:3306/auctionsystem?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: 1204
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:cn/rx/dao/*.xml
logging:
  level:
    cn.rx.dao.mapper: debug
